### ISSUE TITLE
jp_citiesをインポートしようとすると、FileNotFoundErrorが出力される

### ISSUE THREAD

**Issue by mazarimono** [iisaka51/jp_prefecture#1]
jp_citiesを使おうとしたところ、cities.csvがないと出力されました。

<a href="https://gyazo.com/fa20ff1cce9e35667fb8dd3922dc7a9c"><img src="https://i.gyazo.com/fa20ff1cce9e35667fb8dd3922dc7a9c.png" alt="Image from Gyazo" width="684.5714285714286"/></a>

どうも、dataディレクトリがインストールされていないようです。

<a href="https://gyazo.com/a089b65c1196c4b1c059eda3dd823285"><img src="https://i.gyazo.com/a089b65c1196c4b1c059eda3dd823285.png" alt="Image from Gyazo" width="496.57142857142856"/></a>

**Comment by iisaka51** [comment]
This was a bug in setup.py.
I already fix it.

**Comment by mazarimono** [comment]
confirmed.
